library identifier: 'jenkins@main', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/mrigby-cloud/jenkins.git'])

pipeline {
    agent any
    parameters {
        booleanParam(name: 'RC', defaultValue: false, description: 'Is this a Release Candidate?')
    }
    environment {
        VERSION = "0.1.0"        
        VERSION_RC = "rc.2"
    }
    stages {
        stage('Audit tools') {                        
            steps {
                auditTools()
            }
        }
        stage('Build') {
            environment {
                VERSION_SUFFIX = getVersionSuffix rcNumber: env.VERSION_RC, isReleaseCandidate: params.RC
            }
            steps {
              echo "Building version: ${VERSION} with suffix: ${VERSION_SUFFIX}"
            }
        }
        stage('Unit Test') {
            steps {
              echo "Unit testing version: ${VERSION} with suffix: ${VERSION_SUFFIX}"
            }
        }
        stage('Smoke Test') {
            steps {
              echo "Smoke testing version: ${VERSION} with suffix: ${VERSION_SUFFIX}"
            }
        }
        stage('Publish') {
            when {
                expression { return params.RC }
            } 
            steps {
                echo "Publishing VersionPrefix ${VERSION} --version-suffix ${VERSION_RC}" 
            }
        }
    }
}